modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="fft_untold_story"
version="0.1.8"
displayName="FFT: Untold story"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="SaIK"
displayTest="IGNORE_SERVER_VERSION"

# Start of user code block mod configuration
[[mixins]]
config="fft_untold_story.mixins.json"
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.fft_untold_story]]
modId="neoforge"
type="required"
versionRange="[21.8.31,)"
ordering="AFTER"
side="BOTH"

[[dependencies.fft_untold_story]]
modId="minecraft"
type="required"
versionRange="[1.21.8]"
ordering="AFTER"
side="BOTH"


[[dependencies.fft_untold_story]]
modId="jei"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration
